# Generated by Django 5.2.17 on 2026-10-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitytoken',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='securitytoken',
            name='purpose',
            field=models.CharField(choices=[('email_verification', 'Email verification'), ('password_reset', 'Password reset'), ('email_change', 'Email change')], max_length=32),
        ),
    ]
