import { sql } from 'drizzle-orm'

/*
 * Applies server/db/migrations (generated by drizzle-kit) at start-up, on PGlite and on Neon alike.
 * The SQL ships inside the server bundle as Nitro server assets, so it works on Vercel without a
 * separate migrate step (Vercel's Neon credentials are "sensitive" and can't be pulled locally).
 */

type Journal = { entries: { tag: string }[] }

export async function runMigrations(db: Db) {
  const assets = useStorage('assets:migrations')
  const raw = await assets.getItem('meta:_journal.json')
  const journal: Journal = typeof raw === 'string' ? JSON.parse(raw) : (raw as Journal)
  if (!journal?.entries?.length) throw new Error('Migrations journal not found in server assets')

  await db.execute(sql`create table if not exists app_migrations (tag text primary key, applied_at timestamptz not null default now())`)
  const applied = new Set(rowsOf<{ tag: string }>(await db.execute(sql`select tag from app_migrations`)).map((r) => r.tag))

  for (const { tag } of journal.entries) {
    if (applied.has(tag)) continue
    const text = await assets.getItem(`${tag}.sql`)
    if (typeof text !== 'string') throw new Error(`Migration ${tag}.sql not found in server assets`)
    const statements = text
      .split('--> statement-breakpoint')
      .map((s) => s.trim())
      .filter(Boolean)
    await db.transaction(async (tx) => {
      for (const statement of statements) await tx.execute(sql.raw(statement))
      await tx.execute(sql`insert into app_migrations (tag) values (${tag})`)
    })
    console.info(`[db] applied migration ${tag}`)
  }
}
