# Generated by Django 5.2.17 on 2026-10-06 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_order_confirmation_email_sent_at_and_more'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField(help_text='When this period of access begins.')),
                ('package_expires_at', models.DateTimeField(help_text='When learning access ends.')),
                ('account_expires_at', models.DateTimeField(help_text='When the account is closed.')),
                ('expiry_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='billing.order')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='catalog.package')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-package_expires_at'],
                'indexes': [models.Index(fields=['user', '-package_expires_at'], name='entitlement_user_id_0a1f47_idx')],
            },
        ),
    ]
