# Generated by Django 5.2.17 on 2026-10-06 09:24

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Stored in capitals; matching ignores case.', max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage off'), ('fixed', 'Fixed amount off')], default='percentage', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='A percentage (up to 100) or an amount in pounds, depending on the type.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited.', null=True)),
                ('uses_count', models.PositiveIntegerField(default=0, editable=False)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Leave blank for no end date.', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('code'), name='promo_code_unique_case_insensitive'), models.CheckConstraint(condition=models.Q(('discount_value__gt', 0)), name='promo_code_discount_value_positive'), models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'percentage'), _negated=True), ('discount_value__lte', 100), _connector='OR'), name='promo_code_percentage_at_most_100')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Captured at checkout and stored lowercased.', max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.package')),
                ('user', models.ForeignKey(blank=True, help_text='Linked once the account exists. Blank for a guest checkout that was never paid.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='billing.promocode')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='billing_ord_email_597bdb_idx')],
            },
        ),
    ]
