# Generated by Django 5.2.17 on 2026-10-06 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text='How content refers to this sign, e.g. give-way.', unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('warning', 'Warning'), ('regulatory', 'Regulatory'), ('information', 'Information'), ('motorway', 'Motorway')], max_length=20)),
                ('meaning', models.CharField(max_length=300)),
                ('spec', models.JSONField(default=dict, help_text='Shape, colours and symbol. See the drawing rules.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('publish_from', models.DateTimeField(blank=True, help_text='Leave empty to go live as soon as it is published. Otherwise students see it from this time.', null=True)),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('slug', models.SlugField(help_text='Used in links. Changing it breaks saved links.', unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('icon', models.CharField(blank=True, help_text='Icon name the frontend knows.', max_length=40)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers come first.')),
                ('only_for_packages', models.ManyToManyField(blank=True, help_text='Leave empty to include it in every package.', related_name='%(class)ss', to='catalog.package', verbose_name='only for packages')),
                ('published_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'title'],
                'permissions': [('publish_chapter', 'Can publish and unpublish chapters')],
            },
        ),
        migrations.CreateModel(
            name='Subchapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('publish_from', models.DateTimeField(blank=True, help_text='Leave empty to go live as soon as it is published. Otherwise students see it from this time.', null=True)),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('minutes', models.PositiveSmallIntegerField(default=5, help_text='Rough study time, shown to students.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Position within this chapter.')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subchapters', to='learning.chapter')),
                ('only_for_packages', models.ManyToManyField(blank=True, help_text='Leave empty to include it in every package.', related_name='%(class)ss', to='catalog.package', verbose_name='only for packages')),
                ('published_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['chapter', 'order', 'title'],
                'permissions': [('publish_subchapter', 'Can publish and unpublish subchapters')],
            },
        ),
        migrations.CreateModel(
            name='LearningContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('publish_from', models.DateTimeField(blank=True, help_text='Leave empty to go live as soon as it is published. Otherwise students see it from this time.', null=True)),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('content_type', models.CharField(choices=[('theory', 'Theory'), ('video', 'Video'), ('document', 'Document'), ('question', 'Question'), ('hazard', 'Hazard clip')], default='theory', help_text='What kind of material this is.', max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('body_html', models.TextField(blank=True, help_text='Used by theory material.', verbose_name='content')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Position within this subchapter.')),
                ('only_for_packages', models.ManyToManyField(blank=True, help_text='Leave empty to include it in every package.', related_name='%(class)ss', to='catalog.package', verbose_name='only for packages')),
                ('published_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subchapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content', to='learning.subchapter')),
            ],
            options={
                'verbose_name': 'learning content',
                'verbose_name_plural': 'learning content',
                'ordering': ['subchapter', 'order', 'title'],
                'permissions': [('publish_learningcontent', 'Can publish and unpublish learning content')],
            },
        ),
        migrations.AddIndex(
            model_name='subchapter',
            index=models.Index(fields=['chapter', 'order'], name='learning_su_chapter_1ed7e8_idx'),
        ),
        migrations.AddIndex(
            model_name='learningcontent',
            index=models.Index(fields=['subchapter', 'order'], name='learning_le_subchap_ca93b3_idx'),
        ),
    ]
