# Generated by Django 5.2.17 on 2026-10-06 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_learning_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('publish_from', models.DateTimeField(blank=True, help_text='Leave empty to go live as soon as it is published. Otherwise students see it from this time.', null=True)),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('kind', models.CharField(choices=[('practice', 'Practice exam'), ('mock', 'Mock test')], default='practice', max_length=10)),
                ('time_limit_seconds', models.PositiveIntegerField(blank=True, help_text='Leave empty for no time limit.', null=True)),
                ('pass_mark', models.PositiveSmallIntegerField(help_text='How many questions must be right to pass.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('published_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'title'],
                'permissions': [('publish_practiceexam', 'Can publish and unpublish exams')],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Position within this exam.')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='learning.practiceexam')),
            ],
            options={
                'ordering': ['exam', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('publish_from', models.DateTimeField(blank=True, help_text='Leave empty to go live as soon as it is published. Otherwise students see it from this time.', null=True)),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('key', models.SlugField(help_text='How content and bookmarks refer to this question.', unique=True)),
                ('question_type', models.CharField(choices=[('single', 'One answer'), ('multi', 'Several answers'), ('image', 'Road sign answers')], default='single', max_length=10, verbose_name='type')),
                ('prompt', models.TextField(help_text='The question itself.')),
                ('explanation', models.TextField(blank=True, help_text='Shown after answering.')),
                ('chapter', models.ForeignKey(help_text='The area this question belongs to. Students practise and are scored by it.', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='learning.chapter')),
                ('learn_more', models.ForeignKey(blank=True, help_text='Where a student can go to read about this, offered after answering.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='learning.subchapter')),
                ('media_sign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='learning.sign', verbose_name='sign shown with the question')),
                ('published_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['chapter', 'key'],
                'permissions': [('publish_question', 'Can publish and unpublish questions')],
            },
        ),
        migrations.AddField(
            model_name='practiceexam',
            name='questions',
            field=models.ManyToManyField(related_name='exams', through='learning.ExamQuestion', to='learning.question'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_places', to='learning.question'),
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='question',
            field=models.ForeignKey(blank=True, help_text='Used by question material: which question from the bank to ask here.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='learning.question'),
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option_id', models.CharField(help_text='Short id the frontend sends back, such as a, b, c.', max_length=4)),
                ('text', models.CharField(blank=True, max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='learning.question')),
                ('sign', models.ForeignKey(blank=True, help_text='For questions answered with road signs.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answer_options', to='learning.sign')),
            ],
            options={
                'ordering': ['question', 'order', 'option_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='examquestion',
            constraint=models.UniqueConstraint(fields=('exam', 'question'), name='unique_question_per_exam'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'option_id'), name='unique_option_id_per_question'),
        ),
    ]
