# Generated by Django 5.2.17 on 2026-10-07 06:53

import apps.learning.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_progress_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='How staff find this again.', max_length=160)),
                ('kind', models.CharField(choices=[('video', 'Video'), ('document', 'Document'), ('image', 'Image')], max_length=10)),
                ('file', models.FileField(upload_to=apps.learning.models.media_path)),
                ('size_bytes', models.PositiveBigIntegerField(default=0, editable=False)),
                ('content_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='For video. Shown to students before they play it.', null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='media',
            field=models.ForeignKey(blank=True, help_text='Used by video and document material: which file to show.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='learning.mediaasset'),
        ),
    ]
