# Generated by Django 5.2.17 on 2026-10-07 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_media_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('publish_from', models.DateTimeField(blank=True, help_text='Leave empty to go live as soon as it is published. Otherwise students see it from this time.', null=True)),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('max_clicks', models.PositiveSmallIntegerField(default=15, help_text='Clicking more often than this scores nothing for the clip, as in the real test.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('media', models.ForeignKey(help_text='The video from the media library.', on_delete=django.db.models.deletion.PROTECT, related_name='hazard_clips', to='learning.mediaasset')),
                ('published_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'title'],
                'permissions': [('publish_hazardclip', 'Can publish and unpublish hazard clips')],
            },
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='hazard_clip',
            field=models.ForeignKey(blank=True, help_text='Used by hazard material: which clip to show.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='learning.hazardclip'),
        ),
        migrations.CreateModel(
            name='HazardAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveSmallIntegerField()),
                ('top_score', models.PositiveSmallIntegerField(help_text='The most that was available at the time.')),
                ('voided', models.BooleanField(default=False, help_text='True when the clip was clicked through too often.')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazard_attempts', to=settings.AUTH_USER_MODEL)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.hazardclip')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'clip'], name='learning_ha_student_f7fdf1_idx')],
            },
        ),
        migrations.CreateModel(
            name='HazardWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='What the hazard is, for staff. Never shown to students.', max_length=120)),
                ('starts_at', models.DecimalField(decimal_places=2, help_text='Seconds into the clip where the hazard starts developing.', max_digits=6)),
                ('ends_at', models.DecimalField(decimal_places=2, help_text='Seconds into the clip by which it should have been spotted.', max_digits=6)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='learning.hazardclip')),
            ],
            options={
                'ordering': ['clip', 'starts_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='hazard_window_ends_after_it_starts')],
            },
        ),
    ]
