# Generated by Django 5.2.17 on 2026-10-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_hazard_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'ordering': ['-completed_at'], 'verbose_name': 'lesson progress', 'verbose_name_plural': 'lesson progress'},
        ),
    ]
