# Generated by Django 5.2.17 on 2026-10-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='Left blank, this is made from the name.', unique=True)),
                ('description', models.TextField(blank=True)),
                ('duration_days', models.PositiveIntegerField(help_text='How long access lasts, in days (30, 60, 90).')),
                ('price', models.DecimalField(decimal_places=2, help_text='In GBP.', max_digits=8)),
                ('is_featured', models.BooleanField(default=False, help_text='Shown as "most popular" on the storefront.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive packages are hidden and cannot be bought.')),
                ('materials', models.JSONField(blank=True, default=list, help_text='Bullet list of what is included.')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers come first.')),
            ],
            options={
                'ordering': ['display_order', 'price'],
            },
        ),
    ]
